name: Run tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test-coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: unit-testing
              run: make test
